language: python
python: "2.7"
sudo: false
install:
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y libpq-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: python -m py_compile sentry.conf.py
